### ISSUE TITLE
i2c array tx/rx values don't match

### ISSUE THREAD

**Issue by myleskeller** [jdew96/ArduinoSupercomputer#2]
i was hopeful that passing a 2d array to Wire.write() would work knowing the 32-bit limitation of i2c message sizes. unsurprisingly, it doesn't work and will likely require byte transmission in the form of structs since they use contiguous memory. 

this will require a rewrite of how we structure arrays during transmission, reception, and possibly initialization (i.e. malloc).

**Comment by tuanhuynht1** [comment]
I'm about to push a change to sendMatrix().

**Comment by myleskeller** [comment]
neat.
